### ISSUE TITLE
Bluetoothに繋ぐことができません

### ISSUE THREAD

**Issue by tko99999** [satt99/caravelle-build-guide#1]
ファームウェア書き込みまで完了し、それまでのテストでは問題なかった（DFU Targの状態では接続して入力することができた）のですが、Caravelle-BLEあるいはNordic UARTでは表示されません。。

トラブルシューティングも一通り実施したのですが改善されない場合はいかがすればよろしいでしょうか？

**Comment by satt99** [comment]
キットの組み立てに関しご不便おかけし申し訳ありません。
問題の切り分けのため、はじめに状況を整理させてください。
頂いた情報をもとに解決策を一緒に考えたいと思います。

【状況】
・「本体基板の動作確認」でのテストではペアリングができ、マスタおよびスレーブの両方で問題なく入力できた
・「本体へのファームウェア書き込み」を参考に無線通信によるファームウェアアップデートをしたところ、デバイススキャン時に`Caravelle-BLE`と`Nordic UART`のどちらも表示されなくなった
・「トラブルシューティング」を参考に、端末（iphone、PC等）、マスタ、スレーブのそれぞれのペアリング情報を削除したものの、上記症状が改善されなかった

【質問】

> Caravelle-BLEあるいはNordic UARTでは表示されません

ここでいう「表示されない」とは、以下のどちらでしょうか？
1. デバイスのスキャン時に本体基板が認識されない（`Caravelle-BLE`、`Nordic UART`、`DFU Targ`のどれも表示されない）
2. デバイスのスキャン時に、DFUボタンを押していないにも関わらず、`DFU Targ`としてか表示されない

> DFU Targの状態では接続して入力することができた

本来はDFUモードでは文字の入力を行うことができないはずなので、少し気になります。お手数ですがそのときの状況について詳しく説明いただけないでしょうか。

**Comment by tko99999** [comment]
早速のお返事ありがとうございます。また内容に誤りがありましたので、訂正させてください。

現状として、
•マスターが通常起動でもDfuとして起動する（Bluetoothでdfuとして表示され、nRF toolboxでファームウェアのアップデートもできる）
•スレーブはnordicとして認識される
・マスター、スレーブ、接続先の3つで接続情報のリセットをしても改善されない
・マスター、スレーブにはそれぞれ手順に従い最新版のフォームウェアが入っている
・基板のバージョンは2.1（これはあんま関係ないかもですが）
・通電チェックは通ってる

といった状況です。。

**Comment by satt99** [comment]
> •マスターが通常起動でもDfuとして起動する（Bluetoothでdfuとして表示され、nRF toolboxでファームウェアのアップデートもできる）

ファームウェアでエラーが生じるとDFUボタンを押していなくともDFUモードに移行するので、今回のケースもそうではないかという気がします。（開発時は同じような現象によく遭遇しました）

ファームウェアに関して確認です。
1. 今回書き込んだファームウェアはデフォルトのものでしょうか？それともkeymap.c等に変更を加えたオリジナルのものでしょうか？デフォルトの場合はcommitの識別番号を、オリジナルの場合は変更したファイルを共有いただけないでしょうか。こちらで再現できないか試してみたいと思います。
2. NRFSDKはv12.3.0を使用されていますか？ BMP等（v15.0.0）とは異なるバージョンを使用しているので注意が必要です。

**Comment by tko99999** [comment]
> 今回書き込んだファームウェアはデフォルトのものでしょうか？それともkeymap.c等に変更を加えたオリジナルのものでしょうか？デフォルトの場合はcommitの識別番号を、オリジナルの場合は変更したファイルを共有いただけないでしょうか。こちらで再現できないか試してみたいと思います。
ありがとうございます。識別番号はこちらです。cc06220f05239b2fe872ba75ca5046e9d5f7a68
（qmk_firmwareのコミット番号）

> NRFSDKはv12.3.0を使用されていますか？ BMP等（v15.0.0）とは異なるバージョンを使用しているので注意が必要です。
はい、間違いありません。

お手数をおかけしますがよろしくお願いいたします。

**Comment by satt99** [comment]
こちらで `nrf52` ブランチのコミット `cc06220f05239b2fe872ba75ca5046e9d5f7a68` で `default` のキーマップをコンパイル、新品の基板にファームウェアの書き込みを行ったのですが、症状を再現できませんでした、申し訳ありません。

大変お手数なのですが、こちら側でコンパイルしたファームウェアを一度書き込んでいただき、動作するか確認いただけないでしょうか。（リンク先の `caravelle_ble_master_default.zip` を使用してください）
https://github.com/satt99/caravelle-build-guide/releases/tag/Application_v1.0

**Comment by tko99999** [comment]
お返事が遅くなってすみません。。体調を崩しておりました。。。こちら今週の土曜日に行いますので、今しばらくお待ちください。

**Comment by tko99999** [comment]
いただいたリンク先で試してみたのですが、やはりうまくいきません。。

共に購入、組み立てをしていた友人は問題なく完成したので０ではないものの私自身の不手際があったとしても正直検討がつかない状況です。。。

こちらの端末をお送りするので、完成品と交換して頂くなどは難しいでしょうか。。

無理を言って大変申し訳ありませんが何卒ご検討のほどお願い申し上げます。

**Comment by satt99** [comment]
ファームウェアの確認ありがとうございます。

> こちらの端末をお送りするので、完成品と交換して頂くなどは難しいでしょうか。。
承知いたしました。こちらで一度基板を預かった上で原因を調査し、必要に応じて交換品を送付いたします。

続きはBoothのメッセージ機能でお願いいたします。

Boothですが、匿名発送故にこちらからはどのアカウントがtko99999さまのものか特定できません。
大変お手数ですが、tko99999さまの方から一度メッセージをいただけないでしょうか。
よろしくお願いいたします。

**Comment by tko99999** [comment]
ご対応ありがとうございます。。
かしこまりました、Boothにてメッセージをお送りしますのでよろしくお願いします
