### ISSUE TITLE
単三電池駆動バージョンが欲しい

### ISSUE THREAD

**Issue by xxtemita** [satt99/caravelle-build-guide#2]
組み立てて非常に快適に使用させていただいていますが、
表題の件だけ要望としてあげさせていただきたいなと思います。
 (ここに上げて拾っていただけるのかわかりませんが...)

要望の背景としては、
- リチウムコイン電池のランニングコストが高い
- 電池交換のために裏蓋外して電池基盤も一度取り外さないといけないのが煩雑

といったところになります。

ケースの手前側を延長してパームレスト内蔵っぽい感じにして、
そこに電池を収められる作りにしていただけたりすると理想的だなと。

↑のような仕様のケースだけでも頒布していただければ、
電池ボックスや昇圧回路基盤の組み込みといった部分はこちら側でもなんとかなるかなと思っています。
(3Dプリント周りのノウハウは皆無なので...)

**Comment by satt99** [comment]
リプライが遅くなり申し訳ございません。

イメージとしては添付の画像のような感じでしょうか。
この場合だと、パームレスト部の厚みが15mm程度しかないため、電池ケースや裏蓋も含めて考えると単三電池を収めるのは難しいと思われます。

ただ、単四電池であれば工夫しだいで収まるかもしれません。
下記画像のパームレスト部のSTEPファイルをアップロードするので、それをもとに電池を収める部分（電池＋昇圧回路を収める穴や裏蓋等）をモデリングしていただければ、こちらでトップケースとの結合および試作品のケースを印刷することも可能です。

よろしくお願いいたします。

![image](https://user-images.githubusercontent.com/39004890/126053867-4abca726-1db1-4b68-b248-be8e44485f6e.png)

- パームレストSTEP、F3D
[palmrest.zip](https://github.com/satt99/caravelle-build-guide/files/6835590/palmrest.zip)

**Comment by satt99** [comment]
一旦Issueを閉じさせていただきます。
